async function chat(message){
  if(!message.channel.type === 'GUILD_TEXT' || message.author.bot) return;  
    if(message.content.match(/ぽーい|ポーイ|テーい|てーい/)){
      message.channel.send("ぺポーイ");
      return;
    }
    if(message.content.match(/ええ|えぇ/)){
      message.reply("(｀・ω・´)？");
      return;
    }
    if(message.content.match(/ヨロ|よろ/)){
      message.channel.send("よろ〜");
      return;
    }
    if(message.content.match(/そうですか|ソウデスカ/)){
      message.channel.send("fmfm");
      return;
    }
    if(message.content.match(/うぇ/)){
      message.channel.send("うう..");
      return;
    }
    if(message.content.match(/草|kusa|くさ/)){
      message.channel.send("HAHAH");
      return;
    }
    if(message.content.match(/あるんかな|なんかな/)){
      message.channel.send("hou");
      return;
    }
    if(message.content.match(/www/)){
      message.channel.send("ワールド..ワイドウェブ?");
      return;
    }
    if(message.content.match(/ぺぺ|ぽ？|ぴ？|ぺ？/)){
      message.channel.send("ペポ？");
      return;
    }
    if(message.content.match(/なあー|なあ〜|あー|あ〜/)){
      message.channel.send("そーい");
      return;
    }
    if(message.content.match(/行く|いく/)){
      message.channel.send("どこいくペポ？");
      return;
    }
    if(message.content.match(/確かに|たし蟹|たしかに/)){
      message.channel.send("うんうん");
      return;
    }
    if(message.content.match(/わーい|ワーイ/)){
      message.channel.send("わーい");
      return;
    }
    if(message.content.match(/ありがと|あんがと|アリガト|アンガト/)){
      message.channel.send("どもども");
      return;
    }
}

module.exports = chat